-- 코드를 입력하세요 회원 ID, 닉네임, 총거래금액
SELECT U.USER_ID, U.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER U, USED_GOODS_BOARD B
WHERE U.USER_ID = B.WRITER_ID AND STATUS = "DONE"
GROUP BY U.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES